version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: cff-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: cff

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

#gitlab_urls:
#  api: https://forge.hefr.ch/api/v4/
#  download: https://forge.hefr.ch

release:
  github:
    owner: aurel-bul
    name: cff-cli
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

chocolateys:
  - name: cff-cli
    title: CFF CLI
    authors: ORLi1
    project_url: https://github.com/aurel-bul/cff-cli
    url_template: "https://github.com/aurel-bul/cff-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    license_url: https://github.com/aurel-bul/cff-cli/blob/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/aurel-bul/cff-cli
    docs_url: https://github.com/aurel-bul/cff-cli#readme
    bug_tracker_url: https://github.com/aurel-bul/cff-cli/issues
    tags: "cli go SBB CFF FFS"
    summary: CLI tool to view the timetables of the Swiss federal railways (SBB CFF FFS).
    description: |
      CLI tool to view the timetables of the Swiss federal railways (SBB CFF FFS). Fully developed in Go. It uses Opendata Switzerland's Transport API.

    release_notes: "{{ .Changelog }}"

    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"

brews:
  - name: cff-cli
    tap:
      owner: aurel-bul
      name: homebrew-cff_cli
    folder: Formula
    commit_author:
      name: "ORLi1"
      email: "aurelien.bulliard@gmail.com"